import type { Metadata } from "next";
import "./global.css";
import { ThemeProvider } from "@/context/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { Navbar } from "@/components/navigation/navbar";
import { HeadingTitle } from "@/components/heading-title";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
      
              <div className="flex flex-1 flex-col">
                <div className="@container/main flex flex-1 flex-col gap-2">
                  <HeadingTitle />
                  {children}
                </div>
              </div>
          
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
